### ISSUE TITLE
Status phrase should be customisable

### ISSUE THREAD

**Issue by Alex-PK** [hyperium/http#119]
The standard RFC allows to customise the status phrase.

The Response struct should have a method to set a non-predefined status phrase.

**Comment by carllerche** [comment]
Given that this functionality has essentially been removed in HTTP 2.0, I'm not sure it is worth adding additional overhead to support custom status phrases.

**Comment by carllerche** [comment]
Given that there has been no further discussion, I'm going to close this issue due to inactivity.
