### ISSUE TITLE
Dependency `fnv` is missing license information

### ISSUE THREAD

**Issue by raggi** [hyperium/http#133]
This is preventing me from being able to use the current release of the http crate.

See https://github.com/servo/rust-fnv/issues/13

**Comment by carllerche** [comment]
I assume that once that issue is fixed, this should resolve itself as cargo should pull in the license files along with source?

**Comment by seanmonstar** [comment]
The fnv crate [just published 1.0.6](https://crates.io/crates/fnv) that includes a license.
