### ISSUE TITLE
Extract Uri to it's own crate

### ISSUE THREAD

**Issue by theduke** [hyperium/http#137]
The Uri type is very useful in different contexts, not just http clients/servers.

Sadly the Rust ecosystem does not currently have another **maintained** crate for representing Uris: 
* `url` can not represent partial Uris, which the Uri type was explicitly designed for
* `uri` is not maintained (no commit in 2 years, repository is no longer online)

I'm currently in a situation where I need such a type and have nowhere to go.

How feasible would it be to extract the `uri` module into it's own crate and publish it independently?

If this is acceptable for the maintainers, I'd be happy to do the work (extract everything to extra crate, whip up a PR that updates the http crate).

---
Edit:

I've done an initial extraction here: https://github.com/theduke/uri-rs

This would obviously also live in the `hyper` organization.

Tests are passing, the only real things to do here would be to decide on the open questions below and to update the README / docs / ...

---
There are a few open questions with extracting and generalizing the uri module.

I'm going over the code and will be documenting them here:

* HttpTryFrom stub: either just drop this or create a new UriTryFrom stub

* ByteStr: 
type used for optimization reasons. 
it's a bit questionable how useful this type would be in a generic uri crate, but since it's private, it doesn't really matter that much.  (apart from being the only dependency)
The only other location where this is used is for the header name
Options here would be to just duplicate the type (it's a really simple wrapper) or to upstream it to `bytes`
Potentially, the `bytes` dependency could be made optional, and the data represented with either a string or `Bytes` 

* `Protocol` enum: this could be renamed and extended with additional common schemes. typed schemes might be useful for users

* the `uri` name is taken, but since it's not maintained, we could reach out to the author and see if he want's to transfer the crate. Otherwise, an alternative name would be needed:
  - `uris`
  - `uniform_resource_identifier`
  - ... ?

**Comment by carllerche** [comment]
Could you explain the problem with just depending on the `http` crate? It is light on dependencies.

Also, the `uri` implementation isn't really a Uri, but really it is a request target, i.e. an http specific type. It's only named Uri for simplicity.

**Comment by seanmonstar** [comment]
As Carl mentioned, the `http::Uri` is not really a full URI, but a `request-target`. However, most people don't know it by that name, so we went with `Uri`. Additionally, it has been specifically optimized for the use cases in HTTP2. I'm not sure a generic `uri` crate would want that.

**Comment by theduke** [comment]
I guess we'll need a new general purpose uuid crate then.

**Comment by Luro02** [comment]
> Also, the uri implementation isn't really a Uri, but really it is a request target, i.e. an http specific type. It's only named Uri for simplicity.

I think this should be mentioned in the documentation.
