### ISSUE TITLE
Provide `map` for bodies

### ISSUE THREAD

**Issue by aturon** [hyperium/http#143]
Right now, there's no easy way to swap out the body while changing its type (i.e., a `map` method). That's very useful when transforming requests and responses.

**Comment by aturon** [comment]
I'd be happy to make a PR for this if y'all are open to it.

**Comment by carllerche** [comment]
I think everyone wants it, but what to name it? I'm happy w/ `map`, but I think others didn't like that naming.

**Comment by carllerche** [comment]
cc @seanmonstar.

**Comment by olix0r** [comment]
Naming bikeshed: `map_body`, `transform`, `transform_body`

One thing that I think is important to reflect (though I'm unsure which naming does the best job) -- is that the body may not actually be materialized in memory.  you're really just operating on a handle to the body...

**Comment by carllerche** [comment]
To explain more about why I like `map`, I consider `Request` and `Response` essentially metadata wrappers around the payload (the body). As such, they are essentially a wrapper type, so `map` would make sense.

🤷‍♀️

**Comment by seanmonstar** [comment]
Meh, sure, fine. `map`.
