### ISSUE TITLE
Do literal IPv6 addresses supported?

### ISSUE THREAD

**Issue by vi** [hyperium/http#145]
Do [RFC 2732](https://tools.ietf.org/html/rfc2732)-style `http://[1080:0:0:0:8:800:200C:417A]/index.html` links supported by `http`?

I don't see mentions of IPv6 in the documentation or source code.

**Comment by seanmonstar** [comment]
These are the tests covering IPv6 parsing: https://github.com/hyperium/http/blob/master/src/uri/tests.rs#L249-L313
