### ISSUE TITLE
Implement PartialEq / PartialOrd for PathAndQuery

### ISSUE THREAD

**Issue by carllerche** [hyperium/http#149]
PathAndQuery should be comparable against strings. It should probably also include an as_str() fn and a number of other fns that I am forgetting about.

**Comment by kbacha** [comment]
@carllerche Do you think this would be a good beginner issue? I'd like to take a stab at implementing these traits.

**Comment by carllerche** [comment]
Sure, it's not hard, mostly tedious. You can see how [`HeaderValue`](https://github.com/hyperium/http/blob/master/src/header/value.rs#L422-L575) does it.

I would probably stick with string variants and leave out any [u8] variants.

Looking through, it seems that `Scheme` and `Authority` also need comparison / ord implementations.

Also, I would probably start by adding `as_str()` to types that are missing it ([`Authority`](https://github.com/hyperium/http/blob/master/src/uri/authority.rs#L155-L157) seems to have it). then a second PR with Eq, PartialEq, Ord, PartialOrd impls.

Thanks!
