### ISSUE TITLE
New release to 0.1.4?

### ISSUE THREAD

**Issue by myagley** [hyperium/http#158]
Hey everyone. What's the timeline for the next release?

The latest `tower-grpc` codegen depends on some changes to `PathAndQuery` that haven't been published yet. I'm running into issues trying to patch the `http` crate and it would be helpful to have the changes in a released version.

Thanks!

**Comment by carllerche** [comment]
Done: https://crates.io/crates/http/0.1.4

Thanks.

**Comment by myagley** [comment]
Thank you!
