### ISSUE TITLE
Make `http::response::Parts` extensions optional

### ISSUE THREAD

**Issue by Thomasdezeeuw** [hyperium/http#160]
In my use case I don't need extensions, but they do always allocate a hashmap I suggest changing `Parts` from:
```rust 
pub struct Parts {
    pub extensions: Extensions,
    // some fields omitted
}
```

To:

```rust 
pub struct Parts {
    pub extensions: Option<Extensions>,
    // some fields omitted
}
```

This has the same memory usage (https://play.rust-lang.org/?gist=7929f72e3697e316adf5e2fd63123f60&version=stable), but has the benefit of not allocating a hashmap that is not used.

Alternatively this can be moved to `Extensions` internally, to by default not allocate a hashmap and do it on the first insert for example.

This will break some API, e.g. `Response.extensions(_mut)`.

**Comment by Thomasdezeeuw** [comment]
I suggest the same of course for `http::request::Parts`.

**Comment by seanmonstar** [comment]
A `HashMap` is already lazy in its allocation. Creating an empty one does not allocate anything in the heap.

**Comment by carllerche** [comment]
If anything, wrapping it in an `Option` would actually make it worse :) It would increase the field size and add more branching.

**Comment by Thomasdezeeuw** [comment]
I didn't know that `HashMap` was lazy in its allocation, good to know. Then the is an non-issue, thanks guys.
