### ISSUE TITLE
Add support for wasm32-unknown-unknown

### ISSUE THREAD

**Issue by anykao** [hyperium/http#161]
Currently, building against `wasm32-unknown-unknown` would fail. 
See DenisKolodin/yew#102

**Comment by seanmonstar** [comment]
Looks like iovec is a dependency of bytes, to allow for `Buf::bytes_vec`.

**Comment by carllerche** [comment]
iovec has been bumped!

**Comment by carllerche** [comment]
Making sure that bytes works: https://github.com/carllerche/bytes/pull/180

**Comment by seanmonstar** [comment]
Once we know this works, to be able to close this issue, we should add a wasm target to the CI of this crate also.

**Comment by carllerche** [comment]
Ok, bytes CI passed. This lib should probably add a wasm CI step as well.

**Comment by anykao** [comment]
Can confirm it now works. Thanks.
Feel free to close this issue.

**Comment by seanmonstar** [comment]
Should we re-open with the task of adding a CI target of wasm?

**Comment by carllerche** [comment]
sure
