### ISSUE TITLE
Add conversions of HeaderName to HeaderValue

### ISSUE THREAD

**Issue by seanmonstar** [hyperium/http#169]
Generally speaking, all `HeaderName`s are definitely valid `HeaderValue`s. It'd be nice to be able to convert into one without copying. Consider the follow code that should just work:

```rust
map.insert(UPGRADE, WEBSOCKET);
```

I'd expect `From<HeaderName> for HeaderValue`, an `HttpTryFrom for HeaderValue`, and possibly a `HeaderValue::from_name(name: HeaderName)`.

**Comment by kbacha** [comment]
I don't mind taking a stab at this one. But wouldn't converting from a standard that doesn't have inner bytes to a value that requires it mean some amount of copying/writing?

**Comment by seanmonstar** [comment]
Yes and no. It *will* require creating a `Bytes`, but since it's from a static string, it shouldn't need a copy. And, since we know its safe and valid, we can skip the parse/validation in `HeaderValue`.

**Comment by kbacha** [comment]
@seanmonstar https://github.com/hyperium/http/pull/184 😄

**Comment by seanmonstar** [comment]
This was implemented in #184.
