### ISSUE TITLE
Consider a Port type for Uri::port()

### ISSUE THREAD

**Issue by seanmonstar** [hyperium/http#173]
Users may wish to access the port as a string, and not just an integer. We have the string already, so we could provide a newtype around it, `Port`, and a user can then get the bytes themselves, or just ask for the integer.

```rust
fn port(&self) -> Option<Port>;
```

```rust
struct Port<'a> {
    bytes: &'a str,
}

impl<'a> Port<'a> {
    fn as_str(&self) -> &str;

    fn as_u16(&self) -> u16;
}
```

This would be for both `Uri` and `Authority`. Probably introduced as `port_part()`, deprecating `port()` to be replaced in 0.2.

**Comment by carllerche** [comment]
You'd probably want to add a bunch of `PartialEq` implementations as well.

**Comment by briansmith** [comment]
> impl<'a> Port<'a> {
>     fn as_str(&self) -> &str;
> 
>     fn as_u16(&self) -> u16;
> }

These would be better as `From`/`Into` conversions.

**Comment by carllerche** [comment]
No reason to not have both!

**Comment by carllerche** [comment]
The main reason would be to avoid parsing if not needed :shrug:

**Comment by seanmonstar** [comment]
@joshleeb people can already get the `u16` directly, the purpose of this type is for cases where you need the port but in string form. With only the `u16` accessor, you have to allocate a new string via `port.to_string()`, but we already have the `&str` inside the `Authority`.

**Comment by joshleeb** [comment]
Do we want to pull out the valid port number, as a `&str` and store it in the `Port` struct? Something like

```rs
pub fn new(bytes: &'str) -> Option<Port<'a>> {
    bytes
        .rfind(":")
        .and_then(|i| u16::from_str(bytes).ok())
        .and_then(|_| Some(Port{ bytes }))
}
```

Or do we just want to store the raw bytes, even if it's an invalid port number?

**Comment by seanmonstar** [comment]
Hm, yea, since the port isn't verified to be a valid `u16` when parsing the full URI, it'd be weird to get a `Port` that couldn't be turned into a `u16`. Because of that, it does make sense to parse to a `u16` first. Perhaps to not require parsing *again*, the `Port` could have a `u16` field as well.
