### ISSUE TITLE
Questions about `body`

### ISSUE THREAD

**Issue by vitiral** [hyperium/http#196]
I am extremely confused by `body`, and by extension the `Request` and `Response` objects in general:

- `body` is type `T: Serialize/Deserialize`, which it apparently _just returns_. How is it serializing/deserializing it? Does it only use json?
- Is there any way to get or set the "raw body" (i.e. just the string)?

Thanks for the help!

**Comment by vitiral** [comment]
Okay, the docs are maybe helping me a bit:

> For example, the body could be Vec<u8>, a Stream of byte chunks, or a value that has been deserialized.

So I can specify `T: Vec<u8>` or `T: String` (if I expect utf8) and get the raw data right?

**Comment by seanmonstar** [comment]
The `Request` and `Response` types *in this crate* are generic over *any* body type, with no bounds requirements. So, you can have `Request<String>`, `Request<Vec<u8>>`, `Request<ParsedTodo>`, etc. You can use `body()` to get `&T`, and `body_mut()` to get `&mut T`.

**Comment by vitiral** [comment]
but how do you get `&T` without knowing the format it is serialized in?

**Comment by seanmonstar** [comment]
If you require a certain type, you can specify (the same with a generic in anything else, like `Option<T>`, you could require `Option<String>`), or if you only need certain behavior, you can specify bounds.

```rust
fn peek_body_str(req: &Request<String>) {
    println!("request body: {:?}", req.body());
}

fn body_clone<T: Clone>(req: &Request<T>) -> T {
    req.body().clone()
}
```

**Comment by vitiral** [comment]
But it is assuming JSON encoding for deserialization right?

**Comment by seanmonstar** [comment]
I'm not sure what you're referring to. This crate does not put any constraints on the body being able to be JSON.

**Comment by vitiral** [comment]
Okay, I see. This crate doesn't actually know how to serialize/deserialize an http request/response _at all_. It is only for representing those types as rust types.

Thanks!
