### ISSUE TITLE
HeaderMap keys are returned multiple times during iteration

### ISSUE THREAD

**Issue by jtgeibel** [hyperium/http#199]
The documentation for `HeaderMap::keys()` states that "each key will be yielded only once even if it has multiple associated values."  This is not the behavior that I'm seeing with the following test program:

```rust
extern crate http;

use http::header::{HeaderMap, HeaderValue};

fn main() {
    let mut map = HeaderMap::new();
    map.append("a", HeaderValue::from_static("a"));
    map.append("a", HeaderValue::from_static("b"));
    println!("keys().count(): {}", map.keys().count());
    println!("keys_len(): {}", map.keys_len());
}
```

When run, this program prints:

```
keys().count(): 2
keys_len(): 1
```

**Comment by carllerche** [comment]
You are correct. It looks like the `keys` iterator is not implemented correctly.

Is this something that you could look at fixing? It *should* just be a question of implementing an iterator that iterates [`entries`](https://github.com/hyperium/http/blob/master/src/header/map.rs#L43) and yields the key.

**Comment by jtgeibel** [comment]
Thanks for pointing me in the right direction!  I've opened PR #201 and included a test.
