### ISSUE TITLE
Some headers are not recognized

### ISSUE THREAD

**Issue by faulesocke** [hyperium/http#200]
Hey,

I'm currently hunting down a bug in xmlrpc (which depends on reqwest, which depends on hyper, which depends on http). It seems that (at least during my requests) the Content-Length and Content-Type headers are not parsed correctly and are not part of my requests result. Going through the source code and the dependencies, this lead me here. Here is an example program which reproduces the error:

```
extern crate reqwest;

use reqwest::header::{ContentType, ContentLength, UserAgent};

fn main() {
    const URL: &'static str = "http://api.ote.domrobot.com/xmlrpc/";

    let body = Vec::new();
    let body_len = body.len();
    let res = reqwest::Client::new()
        .post(URL)
        .header(UserAgent::new("Rust xmlrpc"))
        .header(ContentType("text/xml; charset=utf-8".parse().unwrap()))
        .header(ContentLength(body_len as u64))
        .body(body)
        .send();

    println!("Result {:?}", res);
}
```

**Comment by seanmonstar** [comment]
The version of hyper that Reqwest uses doesn't yet put its headers through those from this crate, so it's likely not an issue here. Also, seeing that code there doesn't highlight what the actual error is you're seeing.

**Comment by faulesocke** [comment]
I'm sorry. Will file a new more detailed bug in Hyper. It was late last night ;)
