### ISSUE TITLE
Failed to compile (signal: 9, SIGKILL: kill)

### ISSUE THREAD

**Issue by TomasHubelbauer** [hyperium/http#207]
Hey, I have tried to compile a project which uses `http` as an indirect dependency (through actix-web) and the compilation failed on `http`:

```
rustc --crate-name http /root/.cargo/registry/src/github.com-1ecc6299db9ec823/http-0.1.5/src/lib.rs --crate-type lib --emit=dep-info,link -C debuginfo=2 -C metadata=c5fc1c2aeed1cb92 -C extra-filename=-c5fc1c2aeed1cb92 --out-dir /root/www/target/debug/deps -L dependency=/root/www/target/debug/deps --extern fnv=/root/www/target/debug/deps/libfnv-7a9f4c1f096c756f.rlib --extern bytes=/root/www/target/debug/deps/libbytes-5673bf19e74e48d8.rlib --cap-lints allow
```

It just returns `Killed`.

I have got the line about by running `cargo run --verbose` on my project (the project is just actix-web sample code verbatim). This happened to a fresh installation of Ubuntu 16.04 where only Rust and `build-essential` were installed previously.

Is there a way I could try and help debug this further?

**Comment by seanmonstar** [comment]
Hm, that's unfortunate for sure! It sounds like it could be an issue with the rustc compiler, it might be better to file an issue there.

**Comment by TomasHubelbauer** [comment]
Okay, thank you!

**Comment by sfackler** [comment]
A sigkill is almost always caused by the system running out of memory and the kernel OOM killer terminating the process.

**Comment by seanmonstar** [comment]
That's been my experience as well. If it's possible to compile other crates though, it may mean the compiler memory is ballooning in some weird case here.
