### ISSUE TITLE
URI with space in query parses successfully

### ISSUE THREAD

**Issue by df5602** [hyperium/http#208]
As I noticed in [this reddit discussion](https://www.reddit.com/r/rust/comments/8nwbbg/hyper_v012_released/dzzpmwr) earlier today, a string like e.g. "https://api.tvmaze.com/search/shows?q=%22breaking bad%22" parses successfully as URI.

To my knowledge spaces in URIs should also be %-encoded before transmitting the request, and the above should therefore return a parse error.

Do you agree?

**Comment by df5602** [comment]
Nevermind, spaces DO get rejected, seems that I confused myself when trying out different requests...

**Comment by seanmonstar** [comment]
Thanks for verifying!
