### ISSUE TITLE
Parse uri should allow brackets: {}

### ISSUE THREAD

**Issue by drager** [hyperium/http#209]
Hey,

When parsing into a URI I get an `InvalidUriChar` error when my string contains `{}`. This character should not return a error and let the string be parsed successfully. I created a repro here: https://github.com/drager/uri_bug/blob/master/src/main.rs. The assertion should not fail.

Thanks!

**Comment by sfackler** [comment]
Why should this be allowed?

From [RFC 3986](https://tools.ietf.org/html/rfc3986), the grammar for the query portion of a URI is:

```
   query         = *( pchar / "/" / "?" )
   pchar         = unreserved / pct-encoded / sub-delims / ":" / "@"
   unreserved    = ALPHA / DIGIT / "-" / "." / "_" / "~"
   sub-delims    = "!" / "$" / "&" / "'" / "(" / ")"
                 / "*" / "+" / "," / ";" / "="
   pct-encoded   = "%" HEXDIG HEXDIG
```

`{` and `}` are neither unreserved nor sub-delims so they would have to be percent encoded.

**Comment by drager** [comment]
Alright, that makes sense. So I could construct a uri with `{` and `}` like this then: `%7B%7D` or use https://docs.rs/percent-encoding/1.0.1/percent_encoding/index.html for that part.
