### ISSUE TITLE
parse from std::io::Read and impl Read for Request, Response

### ISSUE THREAD

**Issue by akshayknarayan** [hyperium/http#210]
This crate is minimal currently - it essentially only provides types. Is there support for implementing serialization, deserialization, etc?

This of course might have to be configurable depending on the server, but presumably the `hyper` crate must resolve these issues anyway, so it would be nice if that logic was exposed independently of `hyper`.

**Comment by seanmonstar** [comment]
Hey there! I think this is the same as #81, so I'm going to close as duplicate. I believe [this comment](https://github.com/hyperium/http/issues/81#issuecomment-319441325) still accurately describes why this functionality isn't in the crate.
