### ISSUE TITLE
Add Keep-Alive and Proxy-Connection to Headers

### ISSUE THREAD

**Issue by joshleeb** [hyperium/http#211]
From implementing hyperium/hyper#1555, do you think it's worth adding `KEEP_ALIVE`, and `PROXY_CONNECTION` headers to the `http::header` module?

**Comment by seanmonstar** [comment]
I think `Keep-Alive` is uncommon, and the only place I ever see it mentioned is sometimes in MDN docs. I don't think it appears often enough to add it as a variant in the internal match. `Proxy-Connection` I can't really say either way, I haven't read up much on it.

**Comment by seanmonstar** [comment]
As part of some triage, I noticed this is a duplicate of #142, so closing.
