### ISSUE TITLE
http::uri::Authority has no getter for credentials

### ISSUE THREAD

**Issue by kpcyrd** [hyperium/http#212]
According to the docs, the credentials are part of `Authority`, but there is no way to get those. :)

**Comment by seanmonstar** [comment]
I know part of the reason for not existing yet is that the credentials part of an authority are deprecated (from all specs), and it's requested that people please don't put credentials in URIs anymore... :)

**Comment by kpcyrd** [comment]
I think that's up to you :) Since it's deprecated I can see why this might not be added, but as long as it's still in use it might be useful to have it around when porting existing code.

**Comment by seanmonstar** [comment]
I'm going to close this, as I believe there shouldn't be a need to access the credentials. If there's enough demand, pile in here, and we can re-consider.
