### ISSUE TITLE
content negotiation quality value parsing

### ISSUE THREAD

**Issue by astraw** [hyperium/http#213]
It is useful that hyper 0.11 parses quality values from headers such as Accept in accordance with content negotiation as described in [RFC 7231](https://tools.ietf.org/html/rfc7231#section-5.3.1). However, hyper 0.12 has delegated handling of headers to the http crate, which doesn't seem to have this functionality. It would be great to implement it.

This quality value parsing is used by [bui-backend](https://github.com/astraw/bui-backend) and thus the lack of this functionality in the http crate creates a challenge for upgrading bui-backend from hyper 0.11 to 0.12.

**Comment by seanmonstar** [comment]
Typed headers are being discussed in #264.
