### ISSUE TITLE
Consider adding From<uN> for HeaderValue

### ISSUE THREAD

**Issue by seanmonstar** [hyperium/http#217]
It's incredibly common to need to set integer values in headers, but it's currently not super intuitive how to do that. You essentially need to format your integer into a string, and then use `HeaderValue::from_str`. This requires `HeaderValue` to parse the string for invalid bytes, which is most definitely valid since ASCII decimal characters are valid. A naive approach from a user will also mean copying the bytes a couple times from a `String` into headervalue's internal `Bytes`.

We could consider adding `From<usize>`, `From<u64>`, etc for `HeaderValue`, since we know already that it would be a valid header value. And it would also be a big improvement when using the builders:

```rust
Response::builder()
    .header("content-length", buf.len())
    .body(buf)
```

**Comment by carllerche** [comment]
That is fine w/ me
