### ISSUE TITLE
Proposal: server Request/Response metrics

### ISSUE THREAD

**Issue by dmexe** [hyperium/http#241]
Currently, hyper itself and hyper backed HTTP servers/libraries lack proper request/response telemetry (including metrics and tracing). The layered architecture which used in Tokio (eg, transport -> codec -> service) make it difficult to implement by third-party libraries. So, probes should be a part of `Request` and `Response` interfaces.

At least:

1. The time when a request created, it when a codec starts to decode the first byte of the request. 

```rust
trait Request {
   fn created_at(&self) -> Option<Instant>;
}
```

2. A callback mechanism for a response delivery status (including body and streaming). The callback should be invoked when the last bytes of response were flushed on the socket or when response write was failed. The callback could be oneshot channel, or a boxed fn or maybe something else.

```rust
trait Response {
  fn on_write_complete<S: Sender>(&mut self, channel: S);
}
```

**Comment by carllerche** [comment]
Your goal is important, but it is out of this crate’s scope. 

Instead, I would suggest looking at this issue which is attempting to provide a general purpose instrumentation framework so that hyper can provide these metrics. 

https://github.com/tokio-rs/tokio/issues/561
