### ISSUE TITLE
Commit and tag missing for 0.1.13 release

### ISSUE THREAD

**Issue by dekellum** [hyperium/http#254]
The sha1 hash of the commit that was released to crates.io for 0.1.13 is 0da04d10a9b6d4bef8b7b04aaabf07833158c711 (via .cargo_vcs_info.json), but that commit has not been pushed to this repository, nor is there a tag. The source is the same as:

dac4e8f implement fmt::Display for HeaderName (#249)

With an updated CHANGELOG.md:

~~~ diff
@@ -1,3 +1,9 @@
+# 0.1.13 (September 14, 2018)
+
+* impl `fmt::Display` for `HeaderName` (#249)
+* Fix `uri::Authority` parsing when there is no host after an `@` (#248)
+* Fix `Uri` parsing to allow more characters in query strings (#247)
~~~

The master branch of this repository has since diverged (commits after Sept 14.)

**Comment by seanmonstar** [comment]
Woops, I forgot to push them. I've pushed the tag, but the master I had to rebase. The tag is the correct commit.
