### ISSUE TITLE
Empty Method from string is allowed

### ISSUE THREAD

**Issue by theredfish** [hyperium/http#260]
Hello,

After some tests it seems that `Method::from_str("")` returns `Ok`. Shouldn't it be an error of type `InvalidMethod`?

The following test fail :
```
#[test]
fn it_should_return_an_invalid_method_error() {
  assert!(Method::from_str("").is_err());
}
```

**Comment by carllerche** [comment]
This does not seem correct! Would you mind providing a PR to fix this 👍

**Comment by theredfish** [comment]
Yes, I will take a look 👍
