### ISSUE TITLE
SubStatus codes for 401, 403, 404, and 500

### ISSUE THREAD

**Issue by mitchtbaum** [hyperium/http#261]
Could these [HTTP Status codes](http://www.drowningintechnicaldebt.com/RoyAshbrook/archive/2007/10/04/http-status-and-substatus-codes.aspx) fit in http crate?

HTTP Status | HTTP SubStatus | Definition
-- | -- | --
401.x |   | Unauthorized.
401 | 1 | Access is denied due to invalid credentials.
401 | 2 | Access is denied due to server configuration favoring an alternate authentication method.
401 | 3 | Access is denied due to an ACL set on the requested resource.
401 | 4 | Authorization failed by a filter installed on the Web server.
401 | 5 | Authorization failed by an ISAPI/CGI application.
401 | 7 | Access denied by URL authorization policy on the Web server.
403.x |   | Access is denied.
403 | 1 | Execute access is denied.
403 | 2 | Read access is denied.
403 | 3 | Write access is denied.
403 | 4 | SSL is required to view this resource.
403 | 5 | SSL 128 is required to view this resource.
403 | 6 | IP address of the client has been rejected.
403 | 7 | SSL client certificate is required.
403 | 8 | DNS name of the client is rejected.
403 | 9 | Too many clients are trying to connect to the Web server.
403 | 10 | Web server is configured to deny Execute access.
403 | 11 | Password has been changed.
403 | 12 | Client certificate is denied access by the server certificate mapper.
403 | 13 | Client certificate has been revoked on the Web server.
403 | 14 | Directory listing is denied on the Web server.
403 | 15 | Client access licenses have exceeded limits on the Web server.
403 | 16 | Client certificate is ill-formed or is not trusted by the Web server.
403 | 17 | Client certificate has expired or is not yet valid.
403 | 18 | Cannot execute requested URL in the current application pool.
403 | 19 | Cannot execute CGIs for the client in this application pool.
403 | 20 | Passport logon failed.
404.x |   | File or directory not found.
404 | 1 | Web site not accessible on the requested port.
404 | 2 | Web service extension lockdown policy prevents this request.
404 | 3 | MIME map policy prevents this request.
500.x |   | Internal server error.
500 | 11 | Application is shutting down on the Web server.
500 | 12 | Application is busy restarting on the Web server.
500 | 13 | Web server is too busy.
500 | 14 | Invalid application configuration on the server.
500 | 15 | Direct requests for Global.asa are not allowed.
500 | 16 | UNC authorization credentials are incorrect.
500 | 17 | URL authorization store cannot be found.
500 | 18 | URL authorization store cannot be opened.
500 | 100 | Internal ASP error.

**Comment by seanmonstar** [comment]
I don't quite understand what this is asking for. Could expand on the feature request?

**Comment by mitchtbaum** [comment]
These are [nonstandard codes](https://en.wikipedia.org/wiki/HTTP_403#o403_substatus_error_codes_for_IIS), which come from [Microsoft IIS Status and Substatus codes](https://blogs.iis.net/ma_khan/troubleshooting-iis-6-status-and-substatus-codes).  They would greatly help my Rust based web framework.

The only alternative I see is to [modify the reason-phrase in the response header, similarly to tornado](https://stackoverflow.com/questions/38654336/is-it-good-practice-to-modify-the-reason-phrase-of-an-http-response), which sorta matches what [rfc2616](https://www.w3.org/Protocols/rfc2616/rfc2616-sec6.html#sec6.1.1) says to do for 403:
> If the request method was not HEAD and the server wishes to make public why the request has not been fulfilled, it SHOULD describe the reason for the refusal in the entity.

Yet, it also says in [rfc7230](https://tools.ietf.org/html/rfc7230#section-3.1.2) about providing that reason:
> The reason-phrase element exists for the sole purpose of providing a textual description associated with the numeric status code, mostly out of deference to earlier Internet application protocols that were more frequently used with interactive text clients. A client SHOULD ignore the reason-phrase content."

So, it seems a machine code for each status message matches the spirit of the standards better than putting human readable text, which is meant to be ignored.  afaict, this means `StatusCode` would change from a 3 digit integer, as defined by ietf, to a decimal value which encompasses some new codes, as implied by ietf.

**Comment by seanmonstar** [comment]
When the HTTP specs refer to an entity, that usually always means the body of a message.

What does the substatus mean for the protocol? How is rendered and parsed? Why can't they be implemented as a header or in the body?

**Comment by mitchtbaum** [comment]
> When the HTTP specs refer to an entity, that usually always means the body of a message.

> Why can't they be implemented as a header or in the body?

Yea.  I think for 401, the WWW-Authenticate field has space for that info, for 403, the Permission-Denial is either implied or can go in the header or body, and for 500, the Error can go in the header or body too.  About 500, here's some named errors: [error: 121](https://stackoverflow.com/questions/31460357/what-does-an-http-500-error-with-a-121-sub-status-signify) and [system error codes](https://docs.microsoft.com/en-us/windows/desktop/Debug/system-error-codes--0-499-)

Thanks
