### ISSUE TITLE
Add alternative for HeaderMap::entry that cannot error

### ISSUE THREAD

**Issue by seanmonstar** [hyperium/http#267]
Currently, `HeaderMap::entry` is generic over its argument, allowing lazily parsing a `HeaderName`, but means that some of those types might not be valid, so `entry` returns `Result<Entry, Error>`. When alreadying passing a `HeaderName`, it causes code to deal with an error that can never happen, like `headers.entry(HOST).expect("Host is a valid name")`.

It'd be nice to add an alternative method that doesn't return a `Result`, but allows fewer types.

If considered for breaking changes, I'd rename the current to `try_entry`, and make the new alternative just `entry`.

**Comment by carllerche** [comment]
I agree with your proposed breaking change once users can define const header names (this year I think).

**Comment by seanmonstar** [comment]
Closed in #321 with a breaking change.
