### ISSUE TITLE
get_method, get_uri on request::Builder

### ISSUE THREAD

**Issue by kazuk** [hyperium/http#282]
I am writing Azure Storage REST Client and implementing [Authorize with Shared Key](https://docs.microsoft.com/en-us/rest/api/storageservices/authorize-with-shared-key). To create signatures, I need HTTP Method(VERB) , header values, and request URI on the current request. (See  [Blob, Queue, and File Services (Shared Key authorization)](https://docs.microsoft.com/en-us/rest/api/storageservices/authorize-with-shared-key#blob-queue-and-file-services-shared-key-authorization))

I wish to add functions to `request::Builder` 

- `get_method`
- `get_uri`  
- `get_headers`

then I can implement sign_request as bellow
```
fn sign_request(&self, request_builder: Builder ) -> Builder {
    // build string_to_sign
    let string_to_sign =format!( "{}\n.....", request_builder.get_method(). ... );
    // compute signature 
    let signature = ....;
    // add Authorization header to Builder and return it.
    request_builder.header( AUTHORIZATION, "SharedKey {}:{}", self.account_name,signature )
}
```

Can you accept if I send changes?

Or is there any security reason that `request::Builder` shouldn't provide HTTP method etc?

**Comment by seanmonstar** [comment]
On one hand, it certainly *seems* reasonable to want to view what fields have already been set. On the other, I can't remember any *other* builder patterns where getters are included...

**Comment by kazuk** [comment]
https://en.wikipedia.org/wiki/Builder_pattern

C# builder having getter.  because C# property MUST have getter.

C++,Java,etc builder not having getter. 
But user can view current value from builder and update as bellow.

```
let temp_order = builder.build();
let tax = compute_tax( temp_order.item_lines() );
let taxed_order = builder.set_tax(tax).build();
```

in Rust, Builder consumed on first line build() and ends life. last line build() to make compilation error.

- from 'C# Builder' example, Builder have getter when language requirement or limitation hits situation.
- in Rust, Builder causes some of compilation errors, user do 'view current value'. 

IMHO
 'some of compilation errors' as 'language requirement or limitation hits situation' , and then Builder can have getter.

**Comment by carllerche** [comment]
I've wanted this every so often. I would be fine with having `get_*` functions.

**Comment by carllerche** [comment]
Though, if we are to bikeshed a bit, generally Rust doesn't have `get_*` prefix. We obviously can't have no prefix since that fn is used by the setter...

I'm leaning towards just adding `get_` prefixes, but I'm open to other thoughts.

**Comment by kazuk** [comment]
Thank you ,  
I send pull request #284, 

>  generally Rust doesn't have `get_*` prefix. We obviously can't have no prefix since that fn is used by the setter...

Yes, and Yes, 
`get_` prefix for avoid the breaking changes.

**Comment by kazuk** [comment]
Merged! :tada:
