### ISSUE TITLE
Can I directly parsed from TCPStream's Codec ?

### ISSUE THREAD

**Issue by sunhuachuang** [hyperium/http#283]
Maybe I define a codec to read from tcp stream, and parse stream to request/response.

**Comment by carllerche** [comment]
Parsing is left up to crates like https://crates.io/crates/httparse.  The `http` crate only provides the data types. Does this answer your question?

**Comment by sunhuachuang** [comment]
I found that crate, but it doesn't has request's body ? It only has method/path/version/headers fields.

**Comment by carllerche** [comment]
Our plan is to bound HTTP bodies by [`BufStream`](https://github.com/tokio-rs/tokio/blob/master/tokio-buf/src/buf_stream/mod.rs#L25). This isn't fully released yet though.

**Comment by sunhuachuang** [comment]
OK, I got it. Thank you
