### ISSUE TITLE
HTTP Client Trait

### ISSUE THREAD

**Issue by bachp** [hyperium/http#288]
I was wondering if it would make sense the define a trait in the `http` crate that defines a high level interface for doing basic interactions with a HTTP client.

Something really simple like:

```
pub trait Client {
    fn send(&self, &req: Request) -> Response;
}
```
A similar `AsyncClient` could be added later once stabilized.

This would allow libraries that want to consume a HTTP client to just depend on the `http::client::Client` trait and let the consumer choose the implementation (hyper, actix-web, reqwest, ...). The only requirement would be that the HTTP client library used implements the `http::client:Client` trait.

I think the `http` crate would be a good candidate to host this trait as it makes it clear that this is intended as a common minimal interface a consumer can implement.

The idea came up in the context of https://github.com/ramosbugs/oauth2-rs/issues/49

**Comment by carllerche** [comment]
In theory, this is what [Tower](https://github.com/tower-rs/tower) is for. It is still in the early stages, but it would allow pluggable HTTP implementations.

Tower is still in early stages, but I hope 2019 will bring a lot of progress.

An HTTP refinement of `Service` is [here](https://github.com/tower-rs/tower-http).

**Comment by bachp** [comment]
So if I understand correctly the [`tower_http::service::HttpService`](https://tower-rs.github.io/tower-http/tower_http/service/trait.HttpService.html) is intended to be implemented by any http client library. I could for example implement this on top of the [`curl`](https://crates.io/crates/curl) crate?

I still think such a trait would be better located in the `http` crate.

**Comment by carllerche** [comment]
As of now, `http` is limited to data types and does not include any transport concerns.

**Comment by seanmonstar** [comment]
It seems currently that `http` won't include these kinds of traits just yet. So far, `http` can be nicely used in blocking and non-blocking scenarios, and defining a trait would require "picking a side", which we don't really want this basic crate to to do (that and non-blocking IO is likely to see some syntax changes with the stabilizing `async`/`await`).

**Comment by legokichi** [comment]
http-rs released these crates

* https://github.com/http-rs/http-client
* https://github.com/http-rs/http-service
