### ISSUE TITLE
Parse interprets protocol relative url as relative path url

### ISSUE THREAD

**Issue by Insomniak47** [hyperium/http#300]
Parsing of a protocol relative uri string doesn't produce a uri that contains the proper elements in the proper members.

cargo version: 1.33.0 (f099fe94b 2019-02-12)
http version: http = "0.1.16"

Example:
```
    let a = "//en.wikipedia.org/interesting_article".parse::<Uri>().unwrap();
    println!("{:#?}",a);
    println!("Scheme:    {:#?}", a.scheme_part().map_or_else(|| "", |x| x.as_str()));
    println!("Authority: {:#?}", a.authority_part().map_or_else(|| "", |x| x.as_str()));
    println!("Path:      {:#?}", a.path_and_query().map_or_else(|| "", |x| x.as_str()));
```

Expected Output:
```
//en.wikipedia.org/interesting_article
Scheme:    ""
Authority: "en.wikipedia.org"
Path:      "/interesting_article"
```

Actual Output
```
//en.wikipedia.org/interesting_article
Scheme:    ""
Authority: ""
Path:      "//en.wikipedia.org/interesting_article"
```

**Comment by bluetech** [comment]
I don't think this form is allowed in an HTTP [request target](https://tools.ietf.org/html/rfc7230#section-5.3), which is what `http::Uri` represents according to its docstring. You can double-check me by following the EBNF from this link, and down to [RFC3986](https://tools.ietf.org/html/rfc3986). `absolute-form` only allows an `absolute-URI` which does not allow a relative scheme.

If I got it right, I think this change should be reverted, to save people from having to deal with the possibility of scheme being empty.

In regards to the example in the issue, I think it is correct to interpret `//en.wikipedia.org/interesting_article` as an `origin-form` (as in the Actual Output). I just checked what Firefox sends when opening the URL `http://example.com//en.wikipedia.org/interesting_article`, it's

```
GET //en.wikipedia.org/interesting_article HTTP/1.1\r\n
```

**Comment by Insomniak47** [comment]
I agree that this doesn't match the spec for request target. Though @seanmonstar has mentioned that isn't the be all and end all goal of the lib. I personally think it's an ergonomics improvement but I'm biased because I noticed this doing some web scraping and that was the motivation for the fix. If I'm reading RFC3986 S3.3 right it looks like path with no authority isn't allowed to start with two '/'s either. Which would mean it would have to return a parsing error or implement a different solution. I think the former case would be unintuitive.

For comparison: 
It looks like C# splits it into authority/path portions in their URI class (Though it uses file: as the default scheme)
it looks like python splits it as well in https://docs.python.org/2/library/urlparse.html. 

Though neither of them are specifically committed to being request targets.

**Comment by bluetech** [comment]
> I personally think it's an ergonomics improvement but I'm biased because I noticed this doing some web scraping and that was the motivation for the fix.

Can you describe your use case more? For web scarping, the [url crate](https://github.com/servo/rust-url) might be more appropriate.

> If I'm reading RFC3986 S3.3 right it looks like path with no authority isn't allowed to start with two '/'s either. Which would mean it would have to return a parsing error or implement a different solution.

I am reading it differently, using these expansions:

```
request-target -> origin-form
origin-form    -> absolute-path [ "?" query ]
absolute-path  -> 1*( "/" segment )
segment        -> *pchar
```

`segment` can be empty, so `1*( "/" segment )` matches `//foo`.

> Though neither of them are specifically committed to being request targets.

Right, they are more akin to the url crate than to `http::Uri` (which should be `http::RequestTarget` IMO).

**Comment by Insomniak47** [comment]
Specifically:
RFC 3986 S3.3 Para 2
>If a URI does not contain an authority component, then the path cannot begin with two slash characters ("//").

**Comment by Insomniak47** [comment]
Oops hit enter too quickly: 
I think that you're right that a name change would definitely make sense. I don't think it really makes sense to call it a URI in the case where a number of common URI patterns are pulled into an invalid URI representation. 

I think maybe there needs to be a bit of discussion re:The disparity between the name and goal of the type.

**Comment by Insomniak47** [comment]
Sorry for the comment spam - reading into this more. It looks like RFC7230 S2.7 addresses this specifically and essentially notes the behaviour that we're talking about is allowable in this case. Though that would make a request target fundamentally incompatible with generic URI syntax.

I think it comes down to the direction the lib is taking. Though +1 again from me for renaming the type. for compliance w/ request target I think it only makes sense to revert it.

**Comment by bluetech** [comment]
> It looks like RFC7230 S2.7 addresses this specifically

Nice find, I had missed it. For reference, this comment explicitly notes that `absolute-path` accepts `//`:

> An "absolute-path" rule is defined for protocol elements that can contain a non-empty path component.  (This rule differs slightly from the path-abempty rule of RFC 3986, which allows for an empty path to be used in references, and path-absolute rule, which does not allow paths that begin with "//".)

**Comment by seanmonstar** [comment]
Master is starting to look ripe for a release, and this change is part of it. So, if it was a "mistake", we can revert. We need to decide what to do here (cc @carllerche).

**Comment by carllerche** [comment]
I would revert now for the release and continue the discussion.

**Comment by seanmonstar** [comment]
PR to revert for now: https://github.com/hyperium/http/pull/310

Note this isn't meant to declare the previous PR was bad, it just allows us to keep releasing from master while this discussion can continue.

**Comment by Insomniak47** [comment]
Closing because of discussions re:The RFC the type is trying to implement
