### ISSUE TITLE
Next Major Release

### ISSUE THREAD

**Issue by seanmonstar** [hyperium/http#312]
It seems like a good time to start preparing the next major release, since we need to make a couple minor breaking changes, and the ecosystem will need to be updating for `std::future::Future` anyways. There's two *main* questions to consider:

- Should we release 0.2, or go straight to 1.0?
- What should be changed?

**Comment by sfackler** [comment]
The move to async/await and non-owned futures seems like it will be pretty significant API-wise, so it might be worth either a set of RCs or one last 0.x release before going to 1.0.

**Comment by seanmonstar** [comment]
> The move to async/await and non-owned futures seems like it will be pretty significant API-wise

I so far don't expect `http` to have anything actually touching `Future` directly, but maybe it should at some point?

**Comment by carllerche** [comment]
We should release 0.2. If there are no breaking changes, we can always release 1.0 transparently (update 0.2 to re-export 1.0).

I wonder if non-critical aspects should be removed from the "core" crate (like builders). This would allow more iteration w/o breaking types that tend to be included in downstream public APIs.

async / await should have no impact on this crate.

**Comment by seanmonstar** [comment]
There's a [0.2 milestone](https://github.com/hyperium/http/milestone/2) to track what will be done, and [0.2.x branch](https://github.com/hyperium/http/tree/0.2.x) to merge things.
