### ISSUE TITLE
Add an H3 version value

### ISSUE THREAD

**Issue by stammw** [hyperium/http#315]
I'm a contributor of [djc/quinn](https://github.com/djc/quinn), where I'm trying to implement an `H3` stack. 

I decided to use this `http` crate to have a better integration into the rust HTTP ecosystem. 

I need to add an `HTTP/3.0` version value, would you accept a PR for this?

**Comment by seanmonstar** [comment]
See https://github.com/hyperium/http/pull/294

**Comment by stammw** [comment]
Oh, I failed to find this. Thanks.
