### ISSUE TITLE
Replace HttpTryFrom with std::convert::TryFrom

### ISSUE THREAD

**Issue by seanmonstar** [hyperium/http#317]

**Comment by lovasoa** [comment]
Would it be possible to implement `TryFrom`  for all types that implement `HttpTryFrom` without breaking backward compatibility, using conditional compilation ?

https://dev.to/jeikabu/rust-tryfrom-and-conditional-compilation-46fe

**Comment by seanmonstar** [comment]
@lovasoa it's possible! We're just moving towards 0.2 already, and in that branch, we don't need to support the older compiler. See https://github.com/hyperium/http/pull/308#issuecomment-497448119

**Comment by seanmonstar** [comment]
Completed in the 0.2.x branch.
