### ISSUE TITLE
Request builder: remove need for .unwrap()

### ISSUE THREAD

**Issue by Ivshti** [hyperium/http#319]
Currently, as far as I understand, the only point of needing `unwrap()` on the builder is cause `.body()` may be invoked multiple times

Having to `unwrap()` everywhere is inconvenient, especially for codebases that try to avoid `unwrap` and use `.expect` everywhere, ending up with `.expect("builder cannot fail")` everywhere

However, if the `body()` function takes `self` rather than `&self`, this will ensure on a type level that `body()` is never invoked more than once

related: https://github.com/hyperium/http/issues/191

**Comment by olix0r** [comment]
@Ivshti 

> Currently, as far as I understand, the only point of needing unwrap() on the builder is cause .body() may be invoked multiple times

I assume this is in reference to the Request Builder? (And not, for instance, the URI builder?)

The request builder may keep an [error](
https://github.com/hyperium/http/blob/f5e97e4dce222b3fa331627268d276fbcf6f2d0c/src/request.rs#L191
) that is discovered while building the request; and this error is only materialized when `body` is called. So, for what it's worth, there are other error conditions to handle aside from `body` being invoked twice.

**Comment by Ivshti** [comment]
fair enough, I can see now that there are plenty of try_from's that can fail
