### ISSUE TITLE
Zones in link-local IPv6 addresses seems to be not supported.

### ISSUE THREAD

**Issue by vi** [hyperium/http#322]
```rust
extern crate http;

fn main() {
    use http::uri::Uri;
    use std::str::FromStr;
    Uri::from_str("http://[fe80::1%25eth0]:8080/").unwrap();
}
```

`InvalidUri(InvalidAuthority)`.

It parses if I omit the zone index (`%25eth0`), but such URI is expected to be unconnectable by itself.

Should `http` crate support [RFC6874](https://tools.ietf.org/html/rfc6874) and allow link-local IPv6 in URLs?

**Comment by olix0r** [comment]
For what it's worth, `SocketAddr::parse` does not handle this address either: https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=ac423a008035b1e29562123d416fa551

**Comment by vi** [comment]
Yet there is `scope_id` in `SockAddrV6`, an `u32` field.

Filling it in from `parse` requires querying network interfaces information in a platform-specific way although.

**Comment by raggi** [comment]
If we prepared a patch to introduce this feature would it be accepted?
