### ISSUE TITLE
Jsonrpc calls

### ISSUE THREAD

**Issue by AchalaSB** [hyperium/http#334]
Hi, 
I'm trying to connect rust code to ethereum ? Is there any luck in hyperium?? and it should compatible with webassembly as well. 

Is hyper help me for this? but I see no wasm support

Thanks

**Comment by seanmonstar** [comment]
Hello! This library just defines the *types* often used in HTTP applications, like `Request`, `Response`, `StatusCode`, `HeaderMap`, etc.

For a simple and feature-full HTTP client, you could look at [`reqwest`](https://crates.io/crates/reqwest). I don't know what to suggest for WASM, though.
