### ISSUE TITLE
Derive Clone for `Request`

### ISSUE THREAD

**Issue by Luro02** [hyperium/http#340]
Hyper doesn't handle any redirects, so you have to do this manually. This can become quite chaotic with a lot of requests, so I wrote a simple function, that should follow redirects:
```rust
pub async fn fetch<T>(client: Arc<HttpsClient>, request: Request<T>) -> Result<Response<Body>> {
    // send request to server:
    // client: https://docs.rs/hyper/0.12.33/hyper/client/struct.Client.html
    let mut res = client.request(request).await?;
    // follow redirects:
    if res.status() == 302 || res.status() == 307 || res.status() == 308 {
        let redirect_url = res
            .headers()
            .get("location")
            .unwrap()
            .to_str()?
            .parse::<Uri>()?;

        // how do you send a request to the server again? It got consumed by client.request()
        let req_url = request.uri_mut();
        req_url = redirect_url;
        res = client.request(request).await?;
    }

    Ok(res)
}
```
The problem is, that I only get one `Request<T>` and can neither pass it as a reference to `client.request` nor `.clone()` it.
I looked a bit at the declaration of `Request` and it should be possible to derive `Clone` for it with the trait bounds
```rust
impl<T> Clone for Request<T>
where
    T: Clone
```
https://github.com/hyperium/http/blob/78058fdd94f209304660f17c067bf30f253df298/src/request.rs#L156

I am not sure if this issue belongs here or on the hyper repository, but I thought because the struct is from here, that this issue also belongs here. The above code hasn't been run through the compiler, but I hope it's clear why I need clone (technically I could create a new Request from the old Request (with the methods), but this would require a lot of extra code for such a simple thing).

What's the point of `_priv: ()`? It seems to be nowhere used?
https://github.com/hyperium/http/blob/78058fdd94f209304660f17c067bf30f253df298/src/request.rs#L181

**Comment by carllerche** [comment]
I believe `Request` can't be `clone` due to the extension map.

**Comment by seanmonstar** [comment]
> I believe `Request` can't be `clone` due to the extension map.

This is the reason. See https://github.com/hyperium/http/pull/280 for previous discussion.

> What's the point of `_priv: ()`? It seems to be nowhere used?

This defines a private field on the struct, preventing someone from construct a `Parts` by providing all the fields. Without it, then adding a new public field would be a breaking change, since a user doing so would see they are no longer providing all the fields.

**Comment by Luro02** [comment]
Are there any plans on solving this issue? Maybe adding a trait bound with Clone to the map? (most types should implement it...)
