### ISSUE TITLE
Response Reason Phrase is missing

### ISSUE THREAD

**Issue by vchekan** [hyperium/http#345]
Http 1.1 defines that response code is followed by `Reason-Phrase` (RFC 2616, paragraph 6.1):
```
Status-Line = HTTP-Version SP Status-Code SP Reason-Phrase CRLF
...
The Reason-Phrase is intended to give a short textual description of the Status-Code. 
The Status-Code is intended for use by automata and the Reason-Phrase is intended 
for the human user. The client is not required to examine or display the Reason- Phrase. 
```

In REST applications, it is common to put some useful information into Reason-Phrase, for example, `403 Forbidden: request must provide api key in header 'X-mycompany-Api-Key'`.

If response (and error/exception) is ignoring Reason Phrase, it might become very frustrating troubleshooting exercise despite clear explanation sent by server, because the reason would be missing from log files/console and only server side debugging or wire analyzer would help.

Dotnet http client provide access to this data: https://docs.microsoft.com/en-us/dotnet/api/system.web.httpresponse.statusdescription?view=netframework-4.8

**Comment by seanmonstar** [comment]
The reason-phrase is deprecated, and doesn't exist in HTTP2 or HTTP3. Because of this, `http` chooses to only store the 3-digit code, which helps performance.
