### ISSUE TITLE
[Question] WebDAV methods

### ISSUE THREAD

**Issue by ngortheone** [hyperium/http#346]
Hey,

Would you be interested in accepting a PR with methods defined in [WebDAV RFC3918](https://tools.ietf.org/html/rfc4918)?

The standard defines additional http methods
- COPY
- LOCK
- MKCOL
- MOVE
- PROPFIND
- PROPPATCH
- UNLOCK

I know that currently it is possible to get them through extension method, but I thought it would be nice to have them in the box. since this is a standard (maybe as a separately imported mod)

**Comment by seanmonstar** [comment]
My opinion is to leave these out, as they are specific to WebDAV, and not need by *most* HTTP things.

**Comment by WhyNotHugo** [comment]
A problem with using [from_bytes](https://docs.rs/reqwest/latest/reqwest/struct.Method.html#method.from_bytes), is that the methods `is_safe` and `is_idempotent` return results that are wrong. E.g.: `REPORT` and `PROPFIND` are both safe and idempotent, but would return `false`.
