### ISSUE TITLE
Size issue in `HeaderMap::reserve()`

### ISSUE THREAD

**Issue by Qwaz** [hyperium/http#352]
https://github.com/hyperium/http/blob/9c05e391e00474abaa8c14a86bcb0fc5eff1120e/src/header/map.rs#L622-L640

[`usize::next_power_of_two()`](https://doc.rust-lang.org/std/primitive.usize.html#method.next_power_of_two) method silently overflows to 0 in release mode. This makes it possible to shrink the size of the map to 0 with `HeaderMap::reserve()`.

- If the map doesn't contain any entry, it sets the mask value to `usize::MAX` which is inconsistent but doesn't create any immediate harm.
- If the map contains any entry, the code will call `self.grow(0)` and start infinite probing in [this line](https://github.com/hyperium/http/blob/9c05e391e00474abaa8c14a86bcb0fc5eff1120e/src/header/map.rs#L1623).

Another problem is that the assertion for `MAX_SIZE` doesn't exist here, so it is possible to grow the map larger than `MAX_SIZE`.

[Demonstration](https://play.rust-lang.org/?version=stable&mode=release&edition=2018&gist=4c45d68c59cf71191983b691d44e4595)

**Comment by hawkw** [comment]
@Qwaz Am I correct that the potential vulnerability this presents is that an attacker could cause a denial of service by sending a request which causes this overflow?

**Comment by Qwaz** [comment]
@hawkw An attacker can trigger a DoS if they can call `HeaderMap::reserve()` to non-empty `HeaderMap` with a controlled parameter. I believe this scenario is unlikely in practice, but yes, it's theoretically possible.
