### ISSUE TITLE
Unused label will shortly cause build to fail

### ISSUE THREAD

**Issue by BartMassey** [hyperium/http#356]
I'm hoping to shortly change the `unused_labels` lint from `allow` to warn on nightly. This crate has `warnings` set to `deny` and also contains an unused label `'inner`: https://crater-reports.s3.amazonaws.com/pr-66325/try%239007306dd8a80184ce3cb60cdbee0f3b81083ccd/reg/http-0.1.19/log.txt

If you could remove the unused label or change it to `'_inner` or set `unused_labels` to `allow` that would avoid potential breakage once this change is made. Thanks!

**Comment by hellow554** [comment]
For context see https://github.com/rust-lang/rust/pull/66325
