### ISSUE TITLE
Removing Bytes from the public API

### ISSUE THREAD

**Issue by seanmonstar** [hyperium/http#366]
We'd like to disconnect the stability if the `http` crate from the `bytes` crate. However, *using* `Bytes` inside `http`s types facilitates improved performance by reducing copies (especially as headers and URIs can be quite long in the real world).

This proposes a way forward without sacrificing either case:

- Remove all public APIs that uses `Bytes`. This includes `from_shared`, `TryFrom` impls, and `into_bytes` methods.
- Add `from_maybe_shared<T: AsRef<[u8]> + 'static>` constructors to types that would most benefit. These constructors could downcast the value into a `Bytes` if the versions match, and perform a copy if they don't. While a copy not caught at compile-time is unfortunate, the alternatives seem worse.

**Comment by seanmonstar** [comment]
As always, the tricky part is naming:

- `from_maybe_shared`
- `from_shared_maybe_copy`
- `from_maybe_copy`
- ?

**Comment by davidbarsky** [comment]
With `from_bytes` reserved for `from_bytes(&[u8])` (with an implicit `'_` lifetime), `from_maybe_shared<T: AsRef<[u8]> + 'static>` feels like the correct name until Bytes is 1.0, at which point, this could be revisited.

**Comment by DoumanAsh** [comment]
Could we return it to API now that there is stable version of `bytes`?

**Comment by tesaguri** [comment]
> Could we return it to API now that there is stable version of `bytes`?

PR #470 aims to do that.
