### ISSUE TITLE
allow camel case of header name

### ISSUE THREAD

**Issue by xudesheng** [hyperium/http#377]
I'm working on a customized websocket protocol which is using a header name "appKey" for authentication purpose. However, all customized header name is lower cased in this crate. Is there a public API which can enable acceptance of camel case of header name and don't auto lower case it?

I'm trying to use actix-ws, which is relying on this crate.

**Comment by carllerche** [comment]
My understanding is that case sensitive HTTP header names is invalid usage. This might need to be handled outside of `http`.

**Comment by Darkspirit** [comment]
According to HTTP standards your app must compare header names case-insensitively. Otherwise you will definitely run into compatibility problems.

**Comment by seanmonstar** [comment]
For more context, see this previous issue: https://github.com/hyperium/http/issues/228
