### ISSUE TITLE
Reduce or eliminate unsafe code

### ISSUE THREAD

**Issue by DemiMarie** [hyperium/http#398]
Last I checked, this crate used a lot of unsafe code, including a bespoke `HashMap`.  This unsafe code should be eliminated, or at least greatly reduced and audited.

**Comment by adrianos42** [comment]
Unsafe code is not bad if you know what you're doing.

**Comment by LucioFranco** [comment]
I believe most of our unsafe code has been vetted. I think its unlikely we will remove it unless someone is willing to put the time into finding a suitable solution that performs just as well.

That said, I would really like to see more miri tests and using other tools to check our unsafe code. We are very happy to fix any issues found :)

**Comment by carllerche** [comment]
We would be happy to accept PRs that remove unsafe code while maintaining the feature set and performance :+1:
