### ISSUE TITLE
Request::method() doc example uses an invalid dereference

### ISSUE THREAD

**Issue by fuchsnj** [hyperium/http#400]
The example docs for `Request::method()` show an example dereferencing a borrowed `Method`, implying that `Method` is `Copy`, but it's not

https://github.com/hyperium/http/blob/22448cd3f278e44e60b417fb8ae2439d28bfd519/src/request.rs#L473

**Comment by sfackler** [comment]
That example compiles: https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=5b320eeda51dbe3376abbe1d7fd6c258

**Comment by fuchsnj** [comment]
Sorry, you are right. My understanding of Deref/Copy was a bit off.
