### ISSUE TITLE
Can `http::{response,request}::Builder::body` take `Into<T>` instead of `T`

### ISSUE THREAD

**Issue by rylev** [hyperium/http#401]
This would allow the user to write: 
```rust
let response: Response<Body> = Response::builder().body("hello");
```
instead of:
```rust
let response: Response<Body> = Response::builder().body(Body::from("hello"));
```

I don't believe this breaks existing code because of `impl<T> From<T> for T`

**Comment by jplatte** [comment]
> I don't believe this breaks existing code because of `impl<T> From<T> for T`

This is going to break existing code where the type of the expression inside `.body()` is inferred frmo `body`s signature, e.g.

```rust
let response: Response<Body> = Response::builder().body("hello".into());
```

**Comment by seanmonstar** [comment]
I believe this would also require the function to take 2 generics instead of one.
