### ISSUE TITLE
Unexpected panic for malformed URI with brackets

### ISSUE THREAD

**Issue by algesten** [hyperium/http#435]
Doing some fuzzing I encountered this:

```
    let uri = "http://[]@[";
    let uri = uri.parse::<http::Uri>().unwrap(); // is ok
    uri.host(); // panics
```

The panic is `parsing should validate brackets` and come from here: https://github.com/hyperium/http/blob/v0.2.1/src/uri/authority.rs#L486

I expect this to surface as an `Err` and panic on `.unwrap()`.

**Comment by seanmonstar** [comment]
Yep, this looks wrong. Thanks for reporting!
