### ISSUE TITLE
http vs http_types

### ISSUE THREAD

**Issue by drmason13** [hyperium/http#437]
What makes this crate and http_types different? They seem to have very similar goals (foundational types for http to interop between different crates) which would - at first glance - be better met by one "winning out" over the other. For instance I spotted [this http_types issue](https://github.com/http-rs/http-types/issues/137) where http and http_types urls were a little incompatible.

Is it a case of "they're basically the same and are just competing" or are there reasons projects might prefer one over the other? Are there reasons to coexist? (in a perfect world where nobody's hard work would go to waste and nobody's feelings would be hurt!)

I'm sorry if this has been asked a number of times, I couldn't find an issue (open or closed) mentioning http_types at all. Also I don't mean to start anything unpleasant, I'm just curious 👍

**Comment by djc** [comment]
http-types was started by a separate group of people who weren't satisfied with what http has to offer. Read more here:

https://blog.yoshuawuyts.com/async-http/
