### ISSUE TITLE
HeaderMap::get_all() does not split header values on ,

### ISSUE THREAD

**Issue by shikhar** [hyperium/http#491]
[RFC 2616](https://datatracker.ietf.org/doc/html/rfc2616)

> It MUST be possible to combine the multiple header fields into one
   "field-name: field-value" pair, without changing the semantics of the
   message, by appending each subsequent field-value to the first, each
   separated by a comma.

so
   
```
name: value1,value2
```

should be treated the same as

```
name: value1
name: value2
```

**Comment by seanmonstar** [comment]
True, it does not. That is a case where we leave the values alone, and let the user interpret them.

You could iterate on `get_all`, split on `','`, and combine it with `flat_map`.
