### ISSUE TITLE
How to send Response/Request?

### ISSUE THREAD

**Issue by johalun** [hyperium/http#502]
Hey! 

I've been looking through the documentation but I can't find any example of how to actually send a Response. How do I get headers+body as a u8 slice to write to a socket? 

Thanks!

**Comment by seanmonstar** [comment]
This crate is meant to just be the _types_, without a client or server. The hope is that other libraries could depend on some HTTP things without having to declare which client or server implementation a user wants to use. You could use https://hyper.rs as a possible client or server.

**Comment by johalun** [comment]
Ah I see. I looked into Hyper but I need more low level control for my application. I'm using reqwest for incoming request which works great and was hoping to find something similar for generating responses.
