### ISSUE TITLE
Making `http::uri::PathAndQuery::from_shared` public

### ISSUE THREAD

**Issue by WhyNotHugo** [hyperium/http#622]
There's a comment right above the function that says:

```rs
    // Not public while `bytes` is unstable.
```

The [bytes](https://crates.io/crates/bytes) crate has long since reached 1.0 and is stable. Is it okay to now make this method public?

**Comment by tesaguri** [comment]
This has already been tracked as part of #459.

**Comment by WhyNotHugo** [comment]
True, thanks
