### ISSUE TITLE
Change CI to have a single top "ci-pass" requirement

### ISSUE THREAD

**Issue by seanmonstar** [hyperium/http#648]
Simlar to [hyper](https://github.com/hyperium/hyper/blob/6fd696e10974f10b2c6b9d16393bbbfa21c2333f/.github/workflows/CI.yml#L15-L30), this allows us to add new jobs and have them easily be "required", instead of needing to go into the repo settings and manually find each job.

**Comment by dswij** [comment]
Closed by https://github.com/hyperium/http/pull/657
