### ISSUE TITLE
const fn for `StatusCode::as_u16`

### ISSUE THREAD

**Issue by y-haidar** [hyperium/http#665]
Are there plans for this? Would like to use it in constant generics.

https://github.com/hyperium/http/blob/bda93204b3da1a776cf471ed39e8e374cec652e7/src/status.rs#L119-L121

Change to this:

```rust
    pub const fn as_u16(&self) -> u16 {
        (*self).0.get()
    }
```

**Comment by WhyNotHugo** [comment]
See: https://github.com/hyperium/http/pull/680
