### ISSUE TITLE
impl std::error::Error for StatusCode

### ISSUE THREAD

**Issue by fakeshadow** [hyperium/http#672]
Sometimes I want to use status code as an error type like following:
```rust
fn method_guard(req: &Request<()>) -> Result<(), Box<dyn std::error::Error>> {
    if req.method() != Method::GET {
        return Err(Box::new(StatusCode::METHOD_NOT_ALLOWED));
    }
    Ok(())
}
```
Using a new type could resolve the issue but it's an inconvenience for library code where ideally I want to re-export `http` types as much as possible.

**Comment by seanmonstar** [comment]
Hm, but `StatusCode::OK` isn't an error.

You'd be better off using a custom type.
