### ISSUE TITLE
HeaderMap docs show using a string value

### ISSUE THREAD

**Issue by seanmonstar** [hyperium/http#71]
The documentation of `HeaderMap` shows using strings for values, which works in the doc tests because `HeaderMap<T>` is generic over the value. However, if people try to use the same examples in real code, it won't work, because `Request` and `Response` both use `HeaderMap<HeaderValue>`. The docs should probably be updated to show using `HeaderValue`s.

I also kind of wonder if the generic `T` will cause problems elsewhere. If someone just needs to view some headers, and writes `&HeaderMap`, and sees the complaint about a missing generic, will they easily be able to determine it should be `&HeaderMap<HeaderValue`?

Should we export a type alias instead?

**Comment by carllerche** [comment]
It looks like this will be fixed as part of #86?

**Comment by seanmonstar** [comment]
No, the docs still show using a `HeaderMap<&'static str>`.

**Comment by carllerche** [comment]
Docs can be fixed post 0.1, so I will remove the milestone.

**Comment by seanmonstar** [comment]
This is pretty much done. Glancing through, it looks like `HeaderMap::get_mut` shows using a `String` instead of `HeaderValue`, but since you can't mutate a `HeaderValue`, it'd be a less useful example...
