### ISSUE TITLE
Should the lib text be changed to not say "early in lifecycle" and to provide highlights?

### ISSUE THREAD

**Issue by alistaircarscadden** [hyperium/http#723]
The lib.rs doc comment says:

"Note that this crate is still early on in its lifecycle so the support libraries that integrate with the `http` crate are a work in progress! Stay tuned and we'll be sure to highlight crates here in the future." (https://github.com/hyperium/http/blob/master/src/lib.rs#L12)

Since this crate is post-1.0 should this be changed? Should some of the high level client and server crates be highlighted?

**Comment by seanmonstar** [comment]
Yes, those sentences should be removed. We just forgot they exist XD

Would you like to submit a patch?
