### ISSUE TITLE
HeaderMap's `TryFrom<HashMap>` is not generic over the hashing algorithm used

### ISSUE THREAD

**Issue by Qqwy** [hyperium/http#726]
`HeaderMap<T>` implements [`TryFrom<&'a HashMap<K, T>>`](https://docs.rs/http/1.1.0/http/header/struct.HeaderMap.html#impl-TryFrom%3C%26HashMap%3CK,+V%3E%3E-for-HeaderMap%3CT%3E). However, this only covers hashmaps created with the default `S = RandomState` hashing algorithm / state.
If you've gathered some headers from elsewhere (in my case: in a Python library with PyO3) and you want to turn those into a HeaderMap for use in a HTTP client, there is no need to use a HashDoS-resistant hashing function, so being able to use a hashmap with a different hashing function would be great.

As far as I can tell, there is no reason why the current implementation could not work for other hashmaps. The only thing that needs to change is exposing `S` parameter as well in the trait implementation bounds.

**Comment by seanmonstar** [comment]
That makes sense, want to submit a PR?
