### ISSUE TITLE
`Extensions` has over restrictive bounds.

### ISSUE THREAD

**Issue by carloskiki** [hyperium/http#728]
Inserting and removing from a `Extensions` map should not require `Clone` or `Sync`. We never access a reference to the stored value, and we never clone it, hence I do not see why `Extensions` requires these bounds.

I came across this issue as I wanted to store a `oneshot::Sender` that is not `Clone` nor `Sync` for good reasons.

**Comment by sfackler** [comment]
Extensions erases the types inside of it. If it did not require all types to be `Send` and `Clone`, it could not be `Send` or `Clone` itself. See #395 for why the `Clone` bound was added in 1.0.
