### ISSUE TITLE
XHR status codes

### ISSUE THREAD

**Issue by pyfisch** [hyperium/http#79]
The [StatusCode](https://carllerche.github.io/http/http/status/struct.StatusCode.html) claims to allow all codes in the range [0, 65535] but provides no way to set codes outside the recommended range.

**Comment by seanmonstar** [comment]
And worse, there's web platform tests for the code being set to 699.

Regarding the full u16 range, that's a bug in the spec. Most HTTP/1 parsers expect exactly 3 digits. I can't imagine allowing a code that isn't 3 digits, far too much breaks.

**Comment by carllerche** [comment]
Not allowing a way to set the full u16 range is an explicit decision. Is there a reason you think it should be possible to create status codes greater than 999? Technically only 1xx 2xx 3xx 4xx and 5xx are legal (IIRC)

**Comment by pyfisch** [comment]
I'm fine with accepting only codes in the range [100;999]. I think this is sufficient to pass all XHR tests. The docs should be updated accordingly.

**Comment by carllerche** [comment]
Would you be ale to submit a doc PR reflecting the improvements you have in mind?
