### ISSUE TITLE
Make HTTP version optional

### ISSUE THREAD

**Issue by pyfisch** [hyperium/http#83]
In many cases it is not necessary to specify the HTTP version to be used instead it can be chosen by the underlying HTTP implementation.

A hypothetical requests-like client may allow sending requests like this:

```rust
let request = Request::builder().uri("https://www.google.com/about/").body(())?;
let response = requests::fetch(request)?;
```

Currently the request will be for `HTTP_11` but a crate user probably means "use whatever HTTP version you think works best" and in this case would probably prefer if the http client used e.g. HTTP/2, QUIC. But in some other cases users will explicitly set the version to `HTTP_11` because they want to test the page or just don't like the overhead of HTTP/2 for a single connection so ignoring the field for sending requests is not an option either.

I think the version field should be optional: either `Option<Version>` or it could be an extension using the extension mechanism (still part of this crate of course).

**Comment by carllerche** [comment]
IMO, version shouldn't be optional to reduce having that API complexity. When sending a message, a default of 1.1 should be fine.

I think it should be left up to the consumer of the message (client / server impl) to decide how they want to handle versions. There isn't one size fits all, so it doesn't seem appropriate for this crate to dictate.

**Comment by pyfisch** [comment]
And how is "I don't care about the protocol version just get me a response." handled? Not every server will support 1.1 forever.

**Comment by carllerche** [comment]
I believe that it is possible to take a request w/ a lower protocol version and represent it w/ a higher version. So, Version would just default to 1.1 and the client / server would send it through H2. I would think that this is a sane default.

**Comment by pyfisch** [comment]
You mean, the HTTP client should ignore the version field and use the "best" version? For example if the client learns that example.org supports HTTP/2 it would send every request with HTTP/2? To do something different an unspecified client-specific API needs to be used?

**Comment by carllerche** [comment]
Yes, I would imagine that when creating your HTTP client, you would configure how the client should behave around upgrades, etc... you would tell the client to force HTTP 1.1 or implicitly upgrade to HTTP 2.0.

Having this crate enforce anything is out of scope IMO.
