### ISSUE TITLE
Bring back the ContentMD5 standard header

### ISSUE THREAD

**Issue by carllerche** [hyperium/http#85]
It doesn't have to be exposed as a constant but it is still under heavy enough use that I believe it merits a standard header slot.

Removed as part of #67

**Comment by joshtriplett** [comment]
Do we really want to make it easier to use a header that involves MD5? What harm does it do to leave it out?

**Comment by seanmonstar** [comment]
As no one else has commented wishing this existed, I'm eager to just close this. If I'm wrong, pile on here and we can re-open.
